service: {{ cookiecutter.project_slug }}

plugins:
  - serverless-pseudo-parameters
  - serverless-python-requirements
  - serverless-wsgi

provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  timeout: 30
  stage: ${opt:stage, "production"}
  region: eu-west-2
  logRetentionInDays: 30
  apiGateway:
    description: "{{ cookiecutter.project_name }}"
{%- if cookiecutter.vpc == 'y' %}
  vpc:
    securityGroupIds:
      - sg-01991d1c207395dd5
    subnetIds:
      - subnet-0a274d69488f78b8f
      - subnet-016fda42e2c4c85b2
      - subnet-01bff5ccd41216b56
{%- endif %}
#   environment:
#     EXAMPLE_API_KEY: ${ssm:/serverless/{{ cookiecutter.project_slug }}-${opt:stage}/EXAMPLE_API_KEY~true}

custom:
  wsgi:
    app: project.app
    packRequirements: false
  pythonRequirements:
    fileName: requirements/base.txt
    dockerizePip: non-linux
    layer: true
    slim: true
    strip: false

package:
  exclude:
    - "**"
  include:
    - project/**

resources:
  Description: "{{ cookiecutter.project_name }}"

functions:
  app:
    description: "{{ cookiecutter.project_name }}"
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
