service: {{ cookiecutter.project_slug }}

configValidationMode: error

provider:
  name: aws
  architecture: {{ cookiecutter.arch }}
  deploymentMethod: direct
  memorySize: 128
  timeout: 20
  stage: ${opt:stage, "production"}
  region: eu-west-2
  logRetentionInDays: 30
{%- if cookiecutter.function_url != 'y' %}
  httpApi:
    shouldStartNameWithService: true
{%- endif %}
{%- if cookiecutter.vpc == 'y' %}
  vpc:
    securityGroupIds:
      - sg-01991d1c207395dd5
    subnetIds:
      - subnet-0a274d69488f78b8f
      - subnet-016fda42e2c4c85b2
      - subnet-01bff5ccd41216b56
{%- endif %}
  environment:
    SENTRY_DSN: ${ssm:/serverless/${self:service}-${sls:stage}/SENTRY_DSN, ""}
    # EXAMPLE_API_KEY: ${ssm:/serverless/${self:service}-${sls:stage}/EXAMPLE_API_KEY}

resources:
  Description: "{{ cookiecutter.project_name }}"

functions:
  app:
    description: "{{ cookiecutter.project_name }} - app"
{%- if cookiecutter.function_url == 'y' %}
    url: true
{%- else %}
    events:
      - httpApi: '*'
{%- endif %}
    image:
      uri: 253670703218.dkr.ecr.eu-west-2.amazonaws.com/${self:service}-${sls:stage}:latest
