service: {{ cookiecutter.project_slug }}

provider:
  name: aws
  architecture: {{ cookiecutter.arch }}
  deploymentMethod: direct
  memorySize: 128
  timeout: 30
  stage: ${opt:stage, "production"}
  region: eu-west-2
  logRetentionInDays: 30
  apiGateway:
    description: "{{ cookiecutter.project_name }}"
{%- if cookiecutter.vpc == 'y' %}
  vpc:
    securityGroupIds:
      - sg-01991d1c207395dd5
    subnetIds:
      - subnet-0a274d69488f78b8f
      - subnet-016fda42e2c4c85b2
      - subnet-01bff5ccd41216b56
{%- endif %}
  environment:
    SENTRY_DSN: ${ssm:/serverless/${self:service}-${sls:stage}/SENTRY_DSN, ""}
    # EXAMPLE_API_KEY: ${ssm:/serverless/${self:service}-${sls:stage}/EXAMPLE_API_KEY}

resources:
  Description: "{{ cookiecutter.project_name }}"

functions:
  app:
    description: "{{ cookiecutter.project_name }} - app"
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
    image:
      uri: 253670703218.dkr.ecr.eu-west-2.amazonaws.com/${self:service}-${sls:stage}:latest
